version: "3"

services:

  pgAdmin:
    image: 'dpage/pgadmin4'
    restart: always
    ports:
      - 8001:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=art
      - PGADMIN_DEFAULT_PASSWORD=art
    stdin_open: false
    tty: false

  backend:
    image: 'pmt-backend_develop'
    build:
      context: .
      dockerfile: ./docker-build/develop/Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./restServer/:/usr/src/app/
    stdin_open: true
    tty: true


networks:
  default:
    external:
      name: pmt_network