version: "3"

services:
  computing:
    image: 'pmt-compute-module'
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000


networks:
  default:
    external:
      name: pmt_network