version: "3"

services:
  backend:
    image: 'pmt-backend_release'
    build:
      context: .
      dockerfile: ./docker-build/release/Dockerfile
    restart: always
    ports:
      - 8000:8000


networks:
  default:
    external:
      name: pmt_network