version: "3"

services:
  pgAdmin:
    image: 'dpage/pgadmin4'
    restart: always
    volumes:
      - ./pgAdminDB:/var/lib/pgadmin
    ports:
      - 8001:80
    environment: 
      - PGADMIN_DEFAULT_EMAIL=ad
      - PGADMIN_DEFAULT_PASSWORD=ad
    stdin_open: false
    tty: false


networks:
  default:
    external:
      name: pmt_network