# Generated by Django 2.2.4 on 2019-10-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('creator_id', models.ForeignKey(db_column='creator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_creator_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('creator_id', models.ForeignKey(db_column='creator_id', editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_creator_id', to=settings.AUTH_USER_MODEL)),
                ('parent_id', models.ForeignKey(db_column='parent_id', on_delete=django.db.models.deletion.CASCADE, related_name='group_parent_id', to='ums.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPrivileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('authorizer_id', models.ForeignKey(db_column='authorizer_id', editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='groupauthorization_authorizer_id', to=settings.AUTH_USER_MODEL)),
                ('group_id', models.ForeignKey(db_column='group_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupauthorization_group_id', to='ums.Group')),
                ('group_privilege_id', models.ForeignKey(db_column='group_privilege_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupauthorization_group_privilege_id', to='ums.GroupPrivileges')),
                ('user_id', models.ForeignKey(db_column='user_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='groupauthorization_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'group_privilege_id', 'group_id')},
            },
        ),
    ]
