# Generated by Django 2.2.1 on 2019-06-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
