# Generated by Django 2.2.1 on 2019-06-13 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='createdDateTime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updateDateTime',
            new_name='updated',
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastLogin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ums.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ums.UserGroup')),
            ],
            options={
                'unique_together': {('userGroup', 'user')},
            },
        ),
    ]
