# Generated by Django 2.2.4 on 2019-10-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_active1',
            field=models.BooleanField(default=True),
        ),
    ]
