# Generated by Django 2.2.1 on 2019-06-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0002_auto_20190613_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmembers',
            old_name='userGroup',
            new_name='usergroup',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='isActive',
            new_name='isactive',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastLogin',
            new_name='lastlogin',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastName',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='usergroup',
            old_name='isActive',
            new_name='isactive',
        ),
        migrations.AlterUniqueTogether(
            name='groupmembers',
            unique_together={('usergroup', 'user')},
        ),
    ]
