# Generated by Django 2.2.1 on 2019-07-13 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0003_auto_20190620_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='inviter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='inviter', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usercreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
