# Generated by Django 2.2.1 on 2019-07-13 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0004_auto_20190713_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembers',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groupinviter', to=settings.AUTH_USER_MODEL),
        ),
    ]
