# Generated by Django 2.2.1 on 2019-07-13 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0005_auto_20190713_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
