# Generated by Django 2.2.1 on 2019-07-16 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0006_auto_20190713_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPrivileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GroupAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupprivileges', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ums.GroupPrivileges')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usergroup', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ums.UserGroup')),
            ],
            options={
                'unique_together': {('user', 'groupprivileges', 'usergroup')},
            },
        ),
    ]
