version: '3'

services:
  frontend:
    image: 'pmt-frontend-vue'
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:43434
    stdin_open: true
    tty: true

networks:
  default:
    external:
      name: pmt_network
