# Generated by Django 2.2.1 on 2019-06-09 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPrivileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobStatusGroupList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobStatus')),
                ('jobStatusGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobStatusGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDateTime', models.DateTimeField(auto_now_add=True)),
                ('updateDateTime', models.DateTimeField(auto_now=True)),
                ('closeDateTime', models.DateTimeField(null=True)),
                ('childStatusGroup', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.JobStatusGroup')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.JobStatus')),
            ],
        ),
    ]
