# Generated by Django 2.2.4 on 2019-10-06 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(editable=False)),
                ('begin', models.DateTimeField()),
                ('worktime', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('closed', models.DateTimeField(null=True)),
                ('assignee_id', models.ForeignKey(db_column='assignee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_assignee_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('codename', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('trigger', models.CharField(choices=[('e', 'execute'), ('t', 'executeAndLogTime'), ('c', 'close')], default=None, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ReportedWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('worktime', models.DurationField()),
                ('job_id', models.ForeignKey(db_column='job_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='reportedworktime_job_id', to='jobs.Job')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='reportedworktime_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('color', models.CharField(max_length=7)),
                ('creator_id', models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.PROTECT, related_name='milestone_creator_id', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='milestone_job_id', to='jobs.Job')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='child_type_id',
            field=models.ForeignKey(db_column='child_type_id', on_delete=django.db.models.deletion.PROTECT, related_name='job_child_type_id', to='jobs.Type'),
        ),
        migrations.AddField(
            model_name='job',
            name='creator_id',
            field=models.ForeignKey(db_column='creator_id', on_delete=django.db.models.deletion.PROTECT, related_name='job_creator_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='default_baseline_id',
            field=models.ForeignKey(db_column='default_baseline_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_default_baseline_id', to='jobs.Baseline'),
        ),
        migrations.AddField(
            model_name='job',
            name='parent_id',
            field=models.ForeignKey(db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_parent_id', to='jobs.Job'),
        ),
        migrations.AddField(
            model_name='job',
            name='status_id',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.PROTECT, related_name='job_status_id', to='jobs.Status'),
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_start', models.BooleanField()),
                ('job_id', models.ForeignKey(db_column='job_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='execution_job_id', to='jobs.Job')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='execution_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='baseline',
            name='job_id',
            field=models.ForeignKey(db_column='job_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='baseline_job_id', to='jobs.Job'),
        ),
        migrations.CreateModel(
            name='TypeStatuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.Status')),
                ('type_id', models.ForeignKey(db_column='type_id', on_delete=django.db.models.deletion.CASCADE, to='jobs.Type')),
            ],
            options={
                'unique_together': {('type_id', 'status_id')},
            },
        ),
        migrations.CreateModel(
            name='JobAuthorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(db_column='job_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='jobauthorization_job_id', to='jobs.Job')),
                ('privilege_id', models.ForeignKey(db_column='privilege_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='jobauthorization_privilege_id', to='jobs.Privileges')),
                ('user_group_id', models.ForeignKey(db_column='user_group_id', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='jobauthorization_user_group_id', to='ums.Group')),
            ],
            options={
                'unique_together': {('job_id', 'privilege_id', 'user_group_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='baseline',
            unique_together={('number', 'job_id')},
        ),
    ]
