# Generated by Django 2.2.1 on 2019-06-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='closeDateTime',
            new_name='closed',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='createdDateTime',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='updateDateTime',
            new_name='updated',
        ),
    ]
