# Generated by Django 2.2.1 on 2019-06-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobstatustype',
            old_name='jobStatusGroup',
            new_name='jobType',
        ),
    ]
