# Generated by Django 2.2.1 on 2019-06-13 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20190613_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jobs.JobStatus'),
        ),
    ]
