# Generated by Django 2.2.1 on 2019-06-13 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190613_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default='Test name', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='jobstatustype',
            unique_together={('jobType', 'jobStatus')},
        ),
    ]
