# Generated by Django 2.2.1 on 2019-06-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20190609_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPrivileges',
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jobstatusgroup',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
