# Generated by Django 2.2.1 on 2019-06-17 20:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0004_auto_20190613_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='isClosing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='color',
            field=models.CharField(default='#00308F', max_length=7),
        ),
        migrations.AlterField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(null=True)),
                ('color', models.CharField(max_length=7)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobPrivileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(editable=False)),
                ('begin', models.DateTimeField(default=datetime.datetime(2019, 6, 17, 20, 9, 13, 559860, tzinfo=utc))),
                ('interval', models.DurationField(default='8H')),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
            options={
                'unique_together': {('number', 'job')},
            },
        ),
    ]
