# Generated by Django 2.2.1 on 2019-06-17 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190617_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='begin',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 17, 20, 13, 19, 712771, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='color',
            field=models.CharField(default='#00308F', max_length=7),
        ),
    ]
