# Generated by Django 2.2.1 on 2019-06-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20190617_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='begin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='baseline',
            name='interval',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='jobtype',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
