# Generated by Django 2.2.1 on 2019-06-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190618_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='defaultBaseline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defaultBaseline', to='jobs.Baseline'),
        ),
    ]
