# Generated by Django 2.2.1 on 2019-06-20 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_defaultbaseline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='childType',
            new_name='childtype',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='defaultBaseline',
            new_name='defaultbaseline',
        ),
        migrations.RenameField(
            model_name='jobstatus',
            old_name='isClosing',
            new_name='isclosing',
        ),
        migrations.RenameField(
            model_name='jobstatustype',
            old_name='jobStatus',
            new_name='jobstatus',
        ),
        migrations.RenameField(
            model_name='jobstatustype',
            old_name='jobType',
            new_name='jobtype',
        ),
        migrations.AlterUniqueTogether(
            name='jobstatustype',
            unique_together={('jobtype', 'jobstatus')},
        ),
    ]
