# Generated by Django 2.2.1 on 2019-06-21 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ums', '0003_auto_20190620_0850'),
        ('jobs', '0010_auto_20190620_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobprivileges',
            name='job',
        ),
        migrations.AddField(
            model_name='jobprivileges',
            name='codename',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobprivileges',
            name='name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='JobAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('jobprivileges', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobPrivileges')),
                ('usergroup', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ums.UserGroup')),
            ],
            options={
                'unique_together': {('job', 'jobprivileges', 'usergroup')},
            },
        ),
    ]
