# Generated by Django 2.2.1 on 2019-07-01 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0011_auto_20190621_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobstatus',
            name='isclosing',
        ),
        migrations.AddField(
            model_name='jobstatus',
            name='trigger',
            field=models.CharField(choices=[('e', 'execute'), ('c', 'close')], default=None, max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='JobExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('isStart', models.BooleanField()),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
