# Generated by Django 2.2.1 on 2019-07-03 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20190701_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseline',
            name='job',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='jobs.Job'),
        ),
    ]
