# Generated by Django 2.2.1 on 2019-07-03 19:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_auto_20190703_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milestone',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='jobs.Job'),
        ),
    ]
