# Generated by Django 2.2.1 on 2019-07-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20190703_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milestone',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
