# Generated by Django 2.2.1 on 2019-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20190703_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseline',
            old_name='interval',
            new_name='worktime',
        ),
        migrations.AddField(
            model_name='job',
            name='timespent',
            field=models.DurationField(null=True),
        ),
    ]
