# Generated by Django 2.2.1 on 2019-07-04 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20190704_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='timespent',
            new_name='reportedtimespent',
        ),
    ]
