# Generated by Django 2.2.1 on 2019-07-04 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0017_auto_20190704_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobexecution',
            old_name='isStart',
            new_name='isstart',
        ),
        migrations.RemoveField(
            model_name='job',
            name='reportedtimespent',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='jobs.JobStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobstatus',
            name='trigger',
            field=models.CharField(choices=[('e', 'execute'), ('t', 'executeAndLogTime'), ('c', 'close')], default=None, max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='JobReportedWorkTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('worktime', models.DurationField()),
                ('job', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
