# Generated by Django 2.2.1 on 2019-07-13 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20190704_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
