FROM node:lts-alpine
WORKDIR /any-gantt
COPY ./any-gantt/package*.json ./
RUN npm install
RUN npm install --save axios
RUN npm install --save moment

RUN npm install @vue/cli@3.7.0 -g
RUN npm update

COPY ./any-gantt/. .

EXPOSE 80
CMD ["npm", "run", "serve"]
# ENTRYPOINT ["./entrypoint_develop.sh"]

